### ISSUE TITLE
Link to OpenCV conan package

### ISSUE THREAD

**Issue by mega-clueless** [darcamo/conan-vtk#2]
Hi,
Nice work on the conan package.
Did you try to link to OpenCV and then to a project and use it?
I am having some trouble doing it

In my application I am getting a CMAKE error:
CMake Error at build/generators/OpenCV-Target-release.cmake:232 (set_property):
The link interface of target "opencv_viz_DEPS_TARGET"
contains:
vtk::vtk
but the target was not found.

Do you know how to solve it?

Thank you.

**Comment by darcamo** [comment]
Sorry, It's been a long time since I used the recipe myself (I don't use VTK much, and I only needed it for something specific). It was one of the recipes that were more troublesome to create. I had to use `replace_in_file` to modify part of the source code to make it work, and implementing the `package_info` method was done with a lot of trial and error. I would probably try to create a new recipe just to check if things improved and if the recipe can be simpler, but I don't expect to work on this anytime soon.
